version: '3.7'

services:

  {{cookiecutter.project_name}}:
    build:
      context: .
      dockerfile: Dockerfile
{%- if cookiecutter.ssl == "True" %}
    command: ["python", "manage.py", "runsslserver", "0.0.0.0:8000"]
{%- elif cookiecutter.ssl == "False" %}
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
{%- endif %}
    volumes:
      - .:/code
    ports:
{%- if cookiecutter.ssl == "True" %}
      - "127.0.0.1:443:8000"
{% endif %}
{%- if cookiecutter.ssl == "False"" %}
      - "127.0.0.1:80:8000"
{%- endif %}
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=secret
      - DB_SERVICE=postgres
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=true
    links:
{%- if cookiecutter.huey == "True" or cookiecutter.postgres == "True" %}
      - postgres
{%- endif %}
{%- if cookiecutter.huey == "True" %}
      - redis
{%- endif %}
{%- if cookiecutter.huey == "True" or cookiecutter.postgres == "True" %}
    depends_on:
      - postgres
{%- endif %}

{% if cookiecutter.huey == "True" %}
  huey:
    build:
      context: "."
      dockerfile: Dockerfile
    command: ["python", "manage.py", "run_huey", "--huey-verbose"]
    links:
      - redis
    depends_on:
      - redis
      - {{cookiecutter.project_name}}

  redis:
    image: redis:5-stretch
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data/
{% endif %}

{%- if cookiecutter.postgres == "True" %}
  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
{%- endif %}

{%- if cookiecutter.wdb == "True" %}
  wdb:
    image: kozea/wdb
    ports:
      - "1984:1984"
{% endif %}

{%- if cookiecutter.huey == "True" or cookiecutter.postgres == "True" %}
volumes:
{% endif %}
{%- if cookiecutter.huey == "True" %}
  redis-data:
{%- endif %}
{%- if cookiecutter.postgres == "True" %}
  postgres-data:
{%- endif -%}
